export const deploy = {
    login: `/service/login`,
    ecsList: `/service/ecsList`,
    ecsAdd: `/service/ecsAdd`,
    ecsEdit: `/service/ecsEdit`,
    ecsDelete: `/service/ecsDelete`,
    projectList: `/service/projectList`,
    projectAdd: `/service/projectAdd`,
    projectEdit: `/service/projectEdit`,
    projectDelete: `/service/projectDelete`,
    noticeUserList: `/service/noticeUserList`,
    noticeUserAdd: `/service/noticeUserAdd`,
    noticeUserEdit: `/service/noticeUserEdit`,
    noticeUserDelete: `/service/noticeUserDelete`,
    userList: `/service/userList`,
    userAdd: `/service/userAdd`,
    userEdit: `/service/userEdit`,
    userDelete: `/service/userDelete`,
    publish: `/service/publish`,
}
